django/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from members.views import login_view, facebook_login
from members.views import logout_view
from members.views import signup_view

import artist
from config import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # artist/로 시작하는 path가
    # artist.urls모듈을 include하도록 설정
    path('', views.index, name='index'),
    path('artist/', include('artist.urls.views')),
    path('song/', include('song.urls')),
    path('album/', include('album.urls')),

    path('facebook-login/', facebook_login, name='facebook-login'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('signup/', signup_view, name='signup'),
    path('sms/', include('sms.urls')),
    path('mail/', include('mail.urls')),

    path('api/artist/', include('artist.urls.apis')),


]
# settings.METIA_URL('/media/')로 시작하는 요청은
# document_root인 settings.MEDIA_ROOT폴더에서 파일을 찾아 리턴해준다.
urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

django/sms/urls.py
from django.urls import path

from . import views

app_name = 'sms'
urlpatterns = [
    path('send/', views.send_sms, name='send-sms'),
]

django/song/urls.py
from django.urls import path
from . import views

app_name ='song'

urlpatterns =[
    path('', views.song_list, name='song-list'),
    path('search/', views.song_search, name='song-search'),
    path('search/melon', views.song_search_from_melon, name='song-search-from-melon'),
    path('search/melon/add/', views.song_add_from_melon, name='song-add-from-melon'),
]

django/song/models.py
from django.db import models

from album.models import Album
from artist.models import Artist
from album.models import Album
from crawler.song import SongData


class SongManager(models.Manager):
    def update_or_create_from_melon(self, song_id):
        """
        song_id에 해당하는 Song정보를 멜론 사이트에서 가져와 update_or_create를 실행
        이때 해당 Song의 Artist정보도 가져와서 ArtistManager.update_or_create_from_melon도 실행
        :param song_id: 멜론 사이트에서의 곡의 고유Id
        :return: (song instance, Bool(Song created)
        """
        song_data = SongData(song_id)
        song_data.get_detail()

        # artist, _ = Artist.objects.update_or_create_from_melon(song.artist_id)

        # 생성된 Song의 artists필드에 연결된 Artist를 추가
        artist, _ = Artist.objects.update_or_create_from_melon(song_data.artist_id)
        album, _ = Album.objects.update_or_create_from_melon(song_data.album_id)
        song, song_created = self.update_or_create(
            melon_id=song_id,
            album=album,
            defaults={
                'title': song_data.title,
                'genre': song_data.genre,
                'lyrics': song_data.lyrics,

            }
        )
        song.artists.add(artist)
        # song.album.filter(album=None).update(album_id=album.pk)
        # song.album.add(album.id)
        return song, song_created


class Song(models.Model):
    melon_id = models.CharField('멜론 Song ID', max_length=20, blank=True, null=True, unique=True)
    album = models.ForeignKey(
        Album,
        verbose_name='앨범',
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        # default=list,
    )
    artists = models.ManyToManyField(
        Artist,
        verbose_name='아티스트 목록',
        blank=True,
    )
    title = models.CharField(
        '곡 제목',
        max_length=100,
    )
    genre = models.CharField(
        '장르',
        max_length=100,
    )
    lyrics = models.TextField(
        '가사',
        blank=True,
    )

    @property
    def release_date(self):
        # self.album의 release_date를 리턴
        return self.album.release_date

    @property
    def formatted_release_date(self):
        return self.release_date.strftime('%Y.%m.%d')

    def __str__(self):
        # 가수명 - 곡제목 (앨범명)
        # TWICE(트와이스) - Heart Shaker (Merry & Happy)
        # 휘성, 김태우 - 호호호빵 (호호호빵)
        #  artists는 self.album의 속성
        # if self.album:
        #     return '{artists} - {title} ({album})'.format(
        #         artists=', '.join(self.album.artists.values_list('name', flat=True)),
        #         title=self.title,
        #         album=self.album.title,
        #     )
        return self.title

    objects = SongManager()

django/song/views.py
from collections import namedtuple
from typing import NamedTuple

from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render

from album.models import Album
from .models import Song


# Create your views here.
def song_list(request):
    songs = Song.objects.all()
    context = {
        'songs': songs,
    }
    # 전체 Artist목록을 ul>li로 출력
    # 템플릿은 'artist/list.html'을 사용
    # 전달할 context키는 'artist'를 사용

    return render(request, 'song/song_list.html', context)


def song_search(request):
    """
    1.사용할 URL : song/search
     사용할 TEMPLATE ; templates/song/song_search.html
        form안에 input 한개, button한개
        함수에서 return render
    2. get-post 분기
        1.input의 name을 keyword로 지정
        2.이 함수를 request.method가 'get일 떄와 'post'일 떄로 분기
        reuqest.method가 'post'일 떄
            request.post dict의 'keyword'키에 해당하는 값을
            httpresponse로 출력
        request.method가 'get'일 떄
            이전 템플릿 유지
    3. Query filter 로 검색하기
        keyword가 자신의 title에 포함되는 song쿼리셋 생성
        위 쿼리셋을 'songs'변수에 할당
        context dict를 만들고 "songs"키에 songs 변수를 할당
        render의 3번쨰 인수를 만들고 context로 전달
        template에 전달된 'songs'를 출력
            song_search.html을 그대로 사용
    :param request:
    :param title:
    :return:
    #
    # 0219 Homework
    # songs_from_artists
    # songs_from_albums
    # songs_from_title
    # 위 세변수에 위의조건 3개에 부합하는 쿼리셋을 각각 전달
    # 세 변수를 이용해 검색결과를 3단으로 분리해서 출력
    # -> 아티스트로 검색한 노래결과, 앨범으로 검색한 노래결과, 제목으로 검색한 노래결과
    """  # Song과 연결된 Artist의 name에 keyword가 포함되는 경우
    # Song과 연결된 Album의 name에 keyword가 포함되는 경우
    # 를 모두 포함하는 쿼리셋
    # print(request.GET)
    # print(type(request.GET))
    # print(request.GET.get('keyword'))

    # keyword에 빈값이 올 경우 QuerySet을 할당하지 않도록 수정
    # keyword = request.GET.keys()
    # keyword = request.GET['keyword']
    # song목록중 title이 keyword를 포함하는 쿼리셋

    context = {
        'song_infos': [],
    }
    keyword = request.GET.get('keyword')

    # SongInfo = namedtuple('SongInfo', ['type', 'q'])

    class SongInfo(NamedTuple):
        type: str
        q: Q

    if keyword:
        song_infos = (
            SongInfo(
                type='아티스트명',
                q=Q(album__artists__name__contains=keyword)),
            SongInfo(
                type='앨범명',
                q=Q(album__title__contains=keyword)),
            SongInfo(
                type='노래제목',
                q=Q(title__contains=keyword)),
        )

        for type, q in song_infos:
            context['song_infos'].append({
                'type': type,
                'songs': Song.objects.filter(q),
            })
    return render(request, 'song/song_search.html', context)

# else를 없애고 render 를 한번만 사용해서 get/post 요청을 모두처리
# return render(request, 'song/song_search.html')

# songs = Song.objects.filter(
#     Q(album__artists__name__contains=keyword) |
#     Q(title__contains=keyword)|
#     Q(album__title__contains=keyword)
# ).distinct

# filter 뒤의 조건을 Q Objects로 만들어서 for문에서 사용
# songs_from_title = Song.objects.filter(title__contains=keyword)
# songs_from_albums = Song.objects.filter(album__title__contains=keyword)
# songs_from_artists = Song.objects.filter(album__artists__name__contains=keyword)

# 미리선언한 context의 'songs'키에 Queryset을 할당

# context['songs_from_title'] = songs_from_title
# context['songs_from_albums'] = songs_from_albums
# context['songs_from_artists'] = songs_from_artists

# zip
# 1
# for type, songs in zip(('아티스트명', '앨범명', '노래제목'),
#                        (songs_from_artists, songs_from_albums, songs_from_title)):
#     context['song_infos'].append({
#         'type': type,
#         'songs': songs,
#     })
# 2
# context['song_infos'].append({
#     'type': '아티스트명',
#     'songs': songs_from_artists
# })
# context['song_infos'].append({
#     'type': '앨범명',
#     'songs': songs_from_albums
# })
# context['song_infos'].append({
#     'type': '노래제목',
#     'songs': songs_from_title
# })

# get 이면 빈상태로 render실행

django/templates/song/song_list.html
{% extends 'base.html' %}
{% load song_extras %}

{% block content %}
<div class="song-list-container">
	<ul class="song-list">
		{% for song in songs %}
		<li class="song-list-item clearfix">
			<div class="li-section clearfix">
				<div class="li-section-title">제목</div>
				<div class="li-section-content">{{ song.title }}</div>
			</div>
			<div class="li-section clearfix">
				<div class="li-section-title">가사</div>
				<div class="li-section-content">{{ song.lyrics|ellipsis_line:4|linebreaksbr }}</div>
			</div>
		</li>
		{% endfor %}
	</ul>
</div>
{% endblock %}

django/templates/song/song_search.html
{% extends 'base.html' %}

{% block content %}
<div>
    <h1><a href="{% url 'song:song-search' %}">노래 검색</a></h1>


    <form action="" method="get">
        <input type="text" name="keyword" value="{{ request.GET.keyword }}">
        <button type="submit">검색</button>
    </form>

    <!--{% include "include/song_search_result.html" with songs=songs_from_title search_condition="노래" only %}-->
    <!--{% include "include/song_search_result.html" with songs=songs_from_albums search_condition="앨범" only %}-->
    <!--{% include "include/song_search_result.html" with songs=songs_from_artists search_condition="아티스트" only %}-->

    <!--
    for문을 순회하면서 include태그를 순회문 안에서 1번만 사용ㅎ해서 3개를 출력할 수 있도록
    view.py를 수정
    -->
    {% for song_info in song_infos%}
        {% include "include/song_search_result.html" with type=song_info.type songs=song_info.songs only %}
    {% endfor %}
</div>
{% endblock %}

django/templates/song/song_search_from_melon.html
{% extends 'base.html' %}

{% block content %}
<div>
	<h3>멜론에서 노래 검색</h3>
	<form action="">
		<input type="text" name="keyword" placeholder="노래 제목">
		<button type="submit">검색</button>
	</form>

	<ul>
	{% for song_info in song_info_list %}
		<li>
			<!--<img src="{{ song_info.url_img_cover }}" alt="">-->
			<span>{{ song_info.song_id }} | {{ song_info.title }}|{{song_info.album_id}} </span>
			<form action="{% url 'song:song-add-from-melon' %}" method="POST">
				{% csrf_token %}
				<input type="hidden" name="song_id" value="{{ song_info.song_id }}">
				<button type="submit">DB에 추가하기</button>
			</form>
		</li>
	{% endfor %}
	</ul>
</div>
{% endblock %}