django/album/urls.py
from django.urls import path
from . import views

app_name = 'album'

urlpatterns = [
    path('', views.album_list, name='album-list'),
    path('<int:album_pk>/', views.album_detail, name='album-detail'),
    path('<int:album_pk>/edit/', views.album_edit, name='album-edit'),
    path('<int:album_pk>/like-toggle/', views.album_like_toggle, name='album-like-toggle'),
    path('add/', views.album_add, name='album-add'),
    path('search/melon/', views.album_search_from_melon, name='album-search-from-melon'),
    path('search/melon/add/', views.album_add_from_melon, name='album-add-from-melon'),
]

django/artist/urls.py
from django.urls import path

from . import views

app_name = 'artist'
urlpatterns = [
    path('', views.artist_list, name='artist-list'),
    path('<int:artist_pk>/', views.artist_detail, name='artist-detail'),
    path('<int:artist_pk>/edit/', views.artist_edit, name='artist-edit'),
    path('<int:artist_pk>/like-toggle/', views.artist_like_toggle, name='artist-like-toggle'),
    path('<int:artist_pk>/add-youtube/', views.artist_add_youtube, name='artist-add-youtube'),
    path('add/', views.artist_add, name='artist-add'),
    path('search/melon/', views.artist_search_from_melon, name='artist-search-from-melon'),
    path('search/melon/add/', views.artist_add_from_melon, name='artist-add-from-melon'),
]

django/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from members.views import login_view, facebook_login
from members.views import logout_view
from members.views import signup_view

import artist
from config import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # artist/로 시작하는 path가
    # artist.urls모듈을 include하도록 설정
    path('', views.index, name='index'),
    path('artist/', include('artist.urls.views')),
    path('song/', include('song.urls')),
    path('album/', include('album.urls')),

    path('facebook-login/', facebook_login, name='facebook-login'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('signup/', signup_view, name='signup'),
    path('sms/', include('sms.urls')),
    path('mail/', include('mail.urls')),

    path('api/artist/', include('artist.urls.apis')),


]
# settings.METIA_URL('/media/')로 시작하는 요청은
# document_root인 settings.MEDIA_ROOT폴더에서 파일을 찾아 리턴해준다.
urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

django/sms/urls.py
from django.urls import path

from . import views

app_name = 'sms'
urlpatterns = [
    path('send/', views.send_sms, name='send-sms'),
]

django/song/urls.py
from django.urls import path
from . import views

app_name ='song'

urlpatterns =[
    path('', views.song_list, name='song-list'),
    path('search/', views.song_search, name='song-search'),
    path('search/melon', views.song_search_from_melon, name='song-search-from-melon'),
    path('search/melon/add/', views.song_add_from_melon, name='song-add-from-melon'),
]

django/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
	<meta charset="UTF-8">
	<meta name="viewport"
	      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Melon archive</title>
	<link rel="stylesheet" href="{% static 'css/base.css' %}">
	<link rel="stylesheet" href="{% static 'css/header.css' %}">
	<link rel="stylesheet" href="{% static 'css/artist-list.css' %}">
	<link rel="stylesheet" href="{% static 'css/signup.css' %}">
	<link rel="stylesheet" href="{% static 'css/song-list.css' %}">
</head>
<body>
	<div class="header-wrap">
		<header class="main-header clearfix">
			<div class="search-container">
				<a href="">
					<img src="{% static 'images/logo.png' %}" alt="">
				</a>
				<div class="input-container">
					<input type="text" class="search-input">
				</div>
			</div>
			<nav class="main-header-nav clearfix">
				<ul class="clearfix">
					<li><a href="{% url 'artist:artist-list' %}">아티스트</a></li>
					<li><a href="{% url 'album:album-list' %}">앨범</a></li>
					<li><a href="{% url 'song:song-list' %}">곡</a></li>
				</ul>
			</nav>
			<nav class="main-header-nav nav-right clearfix">
				<ul class="clearfix">
					{% if user.is_authenticated %}
					<li><a href="">내 정보 ({{ request.user.username }})</a></li>
					<li><a href="{% url 'logout' %}">로그아웃</a></li>
					{% else %}
					<li><a href="{% url 'login' %}">로그인</a></li>
					<li><a href="{% url 'signup' %}">회원가입</a></li>
					{% endif %}
				</ul>
			</nav>
		</header>
	</div>

	<div class="content-block">
		{% block content %}
		{% endblock %}
	</div>
</body>
</html>

django/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div>
	<h1>Index</h1>
</div>
{% endblock %}