django/artist/urls.py
from django.urls import path

from . import views

app_name = 'artist'
urlpatterns = [
    path('', views.artist_list, name='artist-list'),
    path('<int:artist_pk>/', views.artist_detail, name='artist-detail'),
    path('<int:artist_pk>/edit/', views.artist_edit, name='artist-edit'),
    path('<int:artist_pk>/like-toggle/', views.artist_like_toggle, name='artist-like-toggle'),
    path('<int:artist_pk>/add-youtube/', views.artist_add_youtube, name='artist-add-youtube'),
    path('add/', views.artist_add, name='artist-add'),
    path('search/melon/', views.artist_search_from_melon, name='artist-search-from-melon'),
    path('search/melon/add/', views.artist_add_from_melon, name='artist-add-from-melon'),
]

django/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from members.views import login_view, facebook_login
from members.views import logout_view
from members.views import signup_view

import artist
from config import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # artist/로 시작하는 path가
    # artist.urls모듈을 include하도록 설정
    path('', views.index, name='index'),
    path('artist/', include('artist.urls.views')),
    path('song/', include('song.urls')),
    path('album/', include('album.urls')),

    path('facebook-login/', facebook_login, name='facebook-login'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('signup/', signup_view, name='signup'),
    path('sms/', include('sms.urls')),
    path('mail/', include('mail.urls')),

    path('api/artist/', include('artist.urls.apis')),


]
# settings.METIA_URL('/media/')로 시작하는 요청은
# document_root인 settings.MEDIA_ROOT폴더에서 파일을 찾아 리턴해준다.
urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

django/sms/urls.py
from django.urls import path

from . import views

app_name = 'sms'
urlpatterns = [
    path('send/', views.send_sms, name='send-sms'),
]

django/artist/models/artist.py
import json

from django.contrib.auth import get_user_model
from django.db import models
from django.db.models.fields.files import FieldFile
from django.forms import model_to_dict

from .artist_youtube import ArtistYouTube
from .managers import ArtistManager
from config import settings

User = settings.AUTH_USER_MODEL

__all__ = (
    'Artist',
)


class Artist(models.Model):
    BLOOD_TYPE_A = 'a'
    BLOOD_TYPE_B = 'b'
    BLOOD_TYPE_O = 'o'
    BLOOD_TYPE_AB = 'c'
    BLOOD_TYPE_OTHER = 'x'
    CHOICES_BLOOD_TYPE = (
        (BLOOD_TYPE_A, 'A형'),
        (BLOOD_TYPE_B, 'B형'),
        (BLOOD_TYPE_O, 'O형'),
        (BLOOD_TYPE_AB, 'AB형'),
        (BLOOD_TYPE_OTHER, '기타'),
    )
    melon_id = models.CharField(
        '멜론 Artist ID',
        max_length=20,
        blank=True,
        null=True,
        unique=True,
    )
    img_profile = models.ImageField(
        '프로필 이미지',
        upload_to='artist',
        blank=True,
    )
    name = models.CharField(
        '이름',
        max_length=50,
    )
    real_name = models.CharField(
        '본명',
        max_length=30,
        blank=True,
    )
    nationality = models.CharField(
        '국적',
        max_length=50,
        blank=True,
    )
    birth_date = models.DateField(
        '생년월일',
        blank=True,
        null=True,
    )
    constellation = models.CharField(
        '별자리',
        max_length=30,
        blank=True,
    )
    blood_type = models.CharField(
        '혈액형',
        max_length=1,
        choices=CHOICES_BLOOD_TYPE,
        blank=True,
    )
    intro = models.TextField(
        '소개',
        blank=True,
    )
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        through='ArtistLike',
        related_name='like_artists',
        blank=True
    )
    youtube_videos = models.ManyToManyField(
        ArtistYouTube,
        related_name='artists',
        blank=True,
    )

    objects = ArtistManager()

    class Meta:
        ordering = ['-pk']

    def __str__(self):
        return self.name

    def toggle_like_user(self, user):
        """
        자신의 like_users에 주어진 user가 존재하지 않으면
            like_users에 추가한다
        만약 이미 존재하면 없앤다.
        :param user:
        :return:
        """
        # query = ArtistLike.objects.filter(user=user,artist=self)
        # if query.exists():
        #     query.delete()
        #     return False
        # else:
        #     ArtistLike.objects.create(
        #         artist=self,
        #         user=user,
        #     )
        #     return True
        #
        # 자신이 'artist'이며 user가 주어진 user인 ArtistlLike를 가져오거나 없으면 생성
        like, like_created = self.like_user_info_list.get_or_create(user=user)
        if not like_created:
            like.delete()
        return like_created

    def to_json(self):

        # model_to_dict의 결과가 dic
        # 해당 dict의 item을 순회하며
        # json serialize할 때 나는 에러타입의 value를
        # 적절히 변환해서 value에 다시 대입
        user_class = get_user_model()
        ret = model_to_dict(self)

        def convert_value(value):
            if isinstance(value, FieldFile):
                return value.url if value else None
            elif isinstance(value, user_class):
                return value.pk
            elif isinstance(value, ArtistYouTube):
                return value.pk
            return value

        def convert_obj(obj):
            if isinstance(obj, list):
                for index, item in enumerate(obj):
                    obj[index] = convert_obj(item)
            elif isinstance(obj, dict):
                for key, value in obj.items():
                    obj[key] = convert_obj(value)
            return convert_value(obj)

        convert_obj(ret)
        return ret

    class Meta:
        verbose_name_plural = 'Melon-Artist'

django/artist/models/artist_like.py
from datetime import datetime, timezone
from io import BytesIO
from pathlib import Path

import requests
from django.core.files import File
from django.db import models

from .artist import Artist
from config import settings
from crawler.artist import ArtistData

User = settings.AUTH_USER_MODEL
# from members.models import User

from utils.file import download, get_buffer_ext

__all__= (
    'ArtistLike',
)

class ArtistLike(models.Model):
    # Artist와 User(members.User)와의 관계를 나타내는 중개모델
    artist = models.ForeignKey(
        Artist,
        related_name='like_user_info_list',
        on_delete=models.CASCADE,

    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='like_artist_info_list',
        on_delete=models.CASCADE,
    )
    created_date = models.DateTimeField(
        auto_now_add=True
    )

    def __str__(self):
        return 'Artistlike (User: {user}, Artist{artist}), Created{created}'.format(
            # return '"{artist}"가수의 좋아요를 누른({username}, {date})'.format(
            artist=self.artist.name,
            user=self.user.username,
            created=datetime.strftime(self.created_date, '%y.%m.%d'),
        )

    class Meta:
        unique_together = (
            ('artist', 'user'),
        )
        # 좋아요가 중복으로 되는것을 방지

django/artist/models/artist_youtube.py
from django.db import models

from config import settings

User = settings.AUTH_USER_MODEL

__all__ = (
    'ArtistYouTube',
)


class ArtistYouTube(models.Model):
    youtube_id = models.CharField('YouTube ID', primary_key=True, max_length=20)
    title = models.CharField('제목', max_length=200)
    url_thumbnail = models.URLField('커버 이미지 URL', max_length=200, blank=True)

django/artist/models/managers.py
from datetime import datetime, timezone
from io import BytesIO
from pathlib import Path

import requests
from django.core.files import File
from django.db import models

from config import settings
from crawler.artist import ArtistData

User = settings.AUTH_USER_MODEL
# from members.models import User

from utils.file import download, get_buffer_ext

__all__ = (
    'ArtistManager',
)


class ArtistManager(models.Manager):
    def to_dict(self):
        # 기존 쿼리셋 -> self.get_queryset()
        # 특정 쿼리셋의 데이터 리스트를 dict의 list 형태로 반환하도록 함
        # Artist.objects.all().to_dict()
        #   나오는 결과가 list형태로
        #    [
        #        {
        #            'pk':<artist pk>,
        #             'name':<artist name>,
        #             'melon_id':<artist melon_id>,
        #        },
        #        {
        #            'pk':<artist pk>,
        #             'name':<artist name>,
        #             'melon_id':<artist melon_id>,
        #        },
        #
        #    ]
        # artists = self.get_queryset()
        # data = [
        #            {
        #                'pk': artist.pk,
        #                'name': artist.name,
        #                'melon_id': artist.melon_id,
        #            }
        #            for artist in artists
        #        ]
        # return data


        result =[]
        for instance in self.get_queryset():
            result.append(instance.to_json())
        return result

    def update_or_create_from_melon(self, artist_id):
        from .artist import Artist
        artist = ArtistData(artist_id)
        artist.get_detail()
        name = artist.name
        url_img_cover = artist.url_img_cover
        real_name = artist.personal_information.get('본명', '')
        nationality = artist.personal_information.get('국적', '')
        birth_date_str = artist.personal_information.get('생일', '')
        constellation = artist.personal_information.get('별자리', '')
        blood_type = artist.personal_information.get('혈액형', '')

        # blood_type과 birth_date_str이 없을때 처리할것

        # 튜플의 리스트를 순회하며 blood_type을 결정
        for short, full in Artist.CHOICES_BLOOD_TYPE:
            if blood_type.strip() == full:
                blood_type = short
                break
        else:
            # break가 발생하지 않은 경우
            # (미리 정의해놓은 혈액형 타입에 없을 경우)
            # 기타 혈액형값으로 설정
            blood_type = Artist.BLOOD_TYPE_OTHER

        # artist_id가 melon_id에 해당하는 Artist가 이미 있다면
        #   해당 Artist의 내용을 update
        # 없으면 Artist를 생성
        response = requests.get(url_img_cover)
        binary_data = response.content
        temp_file = BytesIO()
        temp_file.write(binary_data)
        temp_file.seek(0)

        artist, artist_created = self.update_or_create(
            melon_id=artist_id,
            defaults={
                'name': name,
                'real_name': real_name,
                'nationality': nationality,
                'birth_date': datetime.strptime(
                    birth_date_str, '%Y.%m.%d') if birth_date_str else None,
                'constellation': constellation,
                'blood_type': blood_type,
            }
        )
        # file_name = Path(url_img_cover).name

        temp_file = download(url_img_cover)

        file_name = '{artist_id}.{ext}'.format(
            artist_id=artist_id,
            ext=get_buffer_ext(temp_file),
        )
        # 중복데이터 제거
        if artist.img_profile:
            artist.img_profile.delete()
        artist.img_profile.save(file_name, File(temp_file))
        return artist, artist_created

django/artist/forms.py
from django.forms import ModelForm
from django import forms

from artist.models import Artist, ArtistYouTube

__all__ = (
    'ArtistForm',
    # 'YoutubeForm',
)


class ArtistForm(forms.ModelForm):
    class Meta:
        model = Artist
        fields = ['img_profile', 'name', 'real_name', 'nationality', 'birth_date', 'constellation', 'blood_type',
                  'intro']
        widgets = {
            'name': forms.TextInput(
                attrs={
                    'class': 'form-control',
                }
            )
        }


# class YoutubeForm(forms.ModelForm):
#     class Meta:
#         model = ArtistYouTube
#         fields = ['youtube_id', 'title', 'url_thumbnail']
#         widgets = {
#             'name': forms.TextInput(
#                 attrs={
#                     'class': 'form-control'
#                 }
#
#             )
#         }

django/artist/urls/views.py
from django.urls import path

from .. import views

app_name = 'artist'
urlpatterns = [
    path('', views.artist_list, name='artist-list'),
    path('<int:artist_pk>/', views.artist_detail, name='artist-detail'),
    path('<int:artist_pk>/edit/', views.artist_edit, name='artist-edit'),
    path('<int:artist_pk>/like-toggle/', views.artist_like_toggle, name='artist-like-toggle'),
    path('<int:artist_pk>/add-youtube/', views.artist_add_youtube, name='artist-add-youtube'),
    path('add/', views.artist_add, name='artist-add'),
    path('search/melon/', views.artist_search_from_melon, name='artist-search-from-melon'),
    path('search/melon/add/', views.artist_add_from_melon, name='artist-add-from-melon'),
]

django/templates/artist/artist_add.html
{% extends 'base.html' %}

{% block content %}
<div>
	<h3>직접 아티스트 추가</h3>
	<form action="" method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		{% for field in artist_form %}
			<div>
				<label for="{{ field.id_for_label }}">{{ field.label }}</label>
				{{ field }}
				{% if field.errors %}
				<ul>
					{% for error in field.errors %}
					<li>{{ error }}</li>
					{% endfor %}
				</ul>
				{% endif %}
			</div>
		{% endfor %}
		<button type="submit">등록</button>
	</form>

	<hr>

	<!--
		form을 한 개 더 추가
		이 form이 하는 일은 '멜론에서 Artist검색 후 목록 보여주기'를 실행
			-> 목록을 보여주는 일은 artist-search-from-melon이 하는것에 유의
			-> 검색 후에는 URL이 'artist-search-from-melon'부분으로 이동해야 함
	-->
	<h3>멜론에서 아티스트 검색</h3>
	<form action="{% url 'artist:artist-search-from-melon' %}">
		<input type="text" name="keyword" placeholder="아티스트명">
		<button type="submit">검색</button>
	</form>

</div>
{% endblock %}

django/templates/artist/artist_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="artist-list-container">
    <!-- artist-add로의 링크 생성 -->
    <a href="{% url 'artist:artist-add' %}">아티스트 추가</a>
    <ul class="artist-list clearfix">
        <li class="clearfix">
            <a href="">
                <img src="{% if artist.img_profile %}{{ artist.img_profile.url }}{% endif %}" alt="" class="cover">
                <div class="artist-info">
                    <div class="name">{{ artist.name }}</div>
                    <div>{{ artist.nationality }}</div>
                    <div>{{ artist.birth_date }}</div>
                    <div>{{ artist.constellation }}</div>
                    <div>{{ artist.blood_type }}</div>
                </div>

                {% if request.user.is_authenticated %}
                <!-- artist_like_toggle을 실행할 form -->
                <form action="{% url 'artist:artist-like-toggle' artist_pk=artist.pk %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="next-path" value="{{ request.get_full_path }}">
                    {% if request.user in artist.like_users.all %}
                    <button type="submit">좋아요 취소</button>
                    {% else %}
                    <button type="submit">좋아요</button>
                    {% endif %}
                </form>
                {% endif %}
            </a>
        </li>
    </ul>
    <div>
        <h3>저장된 YouTube영상</h3>
        <ul class="youtube-search-list">
            {% for video in artist.youtube_videos.all %}
            <li>
                <a href="https://youtu.be/{{ video.youtube_id }}" target="_blank">
                    <img src="{{ video.url_thumbnail }}" alt="">
                </a>
                <div>{{ video.title }}</div>
            </li>
            {% endfor %}
        </ul>
        <hr>
    </div>
    <div>
        <h3>관련 YouTube영상</h3>
        <ul class="youtube-search-list">
            {% for item in youtube_items %}
            <li>
                <a href="https://youtu.be/{{ item.id.videoId }}" target="_blank">
                    <img src="{{ item.snippet.thumbnails.medium.url }}" alt="">
                </a>
                <div>{{ item.snippet.title }}</div>
                <form action="{% url 'artist:artist-add-youtube' artist_pk=artist.pk %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="youtube_id" value="{{ item.id.videoId }}">
                    <input type="hidden" name="title" value="{{ item.snippet.title }}">
                    <input type="hidden" name="url_thumbnail" value="{{ item.snippet.thumbnails.high.url }}">
                    <input type="hidden" name="next-path" value="{{ request.get_full_path }}">
                    <button type="submit">DB에 저장</button>
                </form>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

django/templates/artist/artist_edit.html
{% extends 'base.html' %}

{% block content %}
<div>
    <h3>아티스트 수정</h3>
    <form action="" method="POST" enctype="multipart/form-data" >
        {% csrf_token %}
        {% for field in artist_form %}
        <div>
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field }}
            {% if field.error %}
            <ul>
                {% for error in field.error %}
                <li>
                    {{ error }}
                </li>
                {% endfor %}
            </ul>
            {% endif %}
        </div>
        {% endfor %}
        <button type="submit">등록</button>
    </form>
</div>
{% endblock %}

django/templates/artist/artist_list.html
{% extends 'base.html' %}
{% block content %}


<div class="artist-list-container">
    <!-- artist-add로 링크 -->
    <a href="{% url 'artist:artist-add' %}">add 창으로 이동 </a>
    <ul class="clearfix">
		{% for artist in artists %}
		<li class="clearfix">
			<a href="{% url 'artist:artist-detail' artist_pk=artist.pk %}">
				<img src="{% if artist.img_profile %}{{ artist.img_profile.url }}{% endif %}" alt="" class="cover">
				<div class="artist-info">
					<div class="name">{{ artist.name }}</div>
					<div>{{ artist.nationality }}</div>
					<div>{{ artist.birth_date }}</div>
					<div>{{ artist.constellation }}</div>
					<div>{{ artist.blood_type }}</div>
					{% if request.user.is_authenticated %}
					<!-- artist_like_toggle을 실행할 form -->
					<form action="{% url 'artist:artist-like-toggle' artist_pk=artist.pk %}" method="POST">
						{% csrf_token %}
						{% if request.user in artist.like_users.all %}
							<button type="submit">좋아요 취소</button>
						{% else %}
							<button type="submit">좋아요</button>
						{% endif %}
					</form>
					{% endif %}
				</div>
			</a>
		</li>
		{% endfor %}    </ul>
</div>
{% endblock %}

django/templates/artist/artist_search_from_melon.html
{% extends 'base.html' %}

{% block content %}
<div>
    <h3>멜론에서 아티스트 검색</h3>
    <form action="">
        <input type="text" name="keyword" placeholder="아티스트명">
        <button type="submit">검색</button>
    </form>

    <ul>
        {% for artist_info in artist_info_list %}
        <li>
            <img src="{{ artist_info.url_img_cover }}" alt="">
            <span>{{ artist_info.artist_id }} | {{ artist_info.name }}</span>
            <form action="{% url 'artist:artist-add-from-melon' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="artist_id" value="{{ artist_info.artist_id }}">
                <!--
                만약 DB에 있는 데이터일 경우에는 DB업데이트라는 문자열을 버튼의 텍스트로 사용
                -->
                {% if artist_info.is_update %}
                    <button type="submit">DB에 업데이트</button>
                {% else %}
                    <button type="submit">DB에 추가하기</button>
                {% endif %}
                <!--<button type="submit">DB에 추가하기</button>-->
            </form>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}