django/album/urls.py
from django.urls import path
from . import views

app_name = 'album'

urlpatterns = [
    path('', views.album_list, name='album-list'),
    path('<int:album_pk>/', views.album_detail, name='album-detail'),
    path('<int:album_pk>/edit/', views.album_edit, name='album-edit'),
    path('<int:album_pk>/like-toggle/', views.album_like_toggle, name='album-like-toggle'),
    path('add/', views.album_add, name='album-add'),
    path('search/melon/', views.album_search_from_melon, name='album-search-from-melon'),
    path('search/melon/add/', views.album_add_from_melon, name='album-add-from-melon'),
]

django/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from members.views import login_view, facebook_login
from members.views import logout_view
from members.views import signup_view

import artist
from config import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # artist/로 시작하는 path가
    # artist.urls모듈을 include하도록 설정
    path('', views.index, name='index'),
    path('artist/', include('artist.urls.views')),
    path('song/', include('song.urls')),
    path('album/', include('album.urls')),

    path('facebook-login/', facebook_login, name='facebook-login'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('signup/', signup_view, name='signup'),
    path('sms/', include('sms.urls')),
    path('mail/', include('mail.urls')),

    path('api/artist/', include('artist.urls.apis')),


]
# settings.METIA_URL('/media/')로 시작하는 요청은
# document_root인 settings.MEDIA_ROOT폴더에서 파일을 찾아 리턴해준다.
urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

django/sms/urls.py
from django.urls import path

from . import views

app_name = 'sms'
urlpatterns = [
    path('send/', views.send_sms, name='send-sms'),
]

django/album/models.py
from datetime import datetime
from django.core.files import File
from django.db import models

from config import settings
from crawler.album import AlbumData

from utils.file import download, get_buffer_ext

User = settings.AUTH_USER_MODEL


class AlbumManager(models.Manager):
    def update_or_create_from_melon(self, album_id):
        album_data = AlbumData(album_id)
        album_data.get_detail()

        album_id = album_data.album_id
        title = album_data.title
        url_img_cover = album_data.url_img_cover
        release_date_str = album_data.release_date

        album, album_created = self.update_or_create(
            melon_id=album_id,
            defaults={
                'title': title,
                'release_date': datetime.strptime(
                    release_date_str, '%Y.%m.%d') if release_date_str else None,
            }
        )

        temp_file = download(url_img_cover)

        file_name = '{album_id}.{ext}'.format(
            album_id=album_id,
            ext=get_buffer_ext(temp_file),
        )
        # 중복데이터 제거
        if album.img_cover:
            album.img_cover.delete()
        album.img_cover.save(file_name, File(temp_file))
        return album, album_created


class Album(models.Model):
    melon_id = models.CharField('멜론 Album ID', max_length=20, blank=True, null=True, unique=True)
    title = models.CharField(
        '앨범명',
        max_length=100,
    )
    img_cover = models.ImageField(
        '커버 이미지',
        upload_to='album',
        blank=True,
    )
    release_date = models.DateField()

    @property
    def genre(self):
        # 장르는 가지고 있는 노래들에서 가져오기
        # ex) Ballad, Dance
        return ', '.join(self.song_set.values_list('genre', flat=True).distinct())

    objects = AlbumManager()

    def __str__(self):
        return self.title

    def toggle_like_user(self, user):
        like, like_created = self.like_user_info_list.get_or_create(user=user)
        if not like_created:
            like.delete()
        return like_created

    class Meta:
        verbose_name_plural = 'Melon-Album'


class AlbumLike(models.Model):
    # album와 User(members.User)와의 관계를 나타내는 중개모델
    album = models.ForeignKey(
        Album,
        related_name='like_user_info_list',
        on_delete=models.CASCADE,

    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='like_album_info_list',
        on_delete=models.CASCADE,
    )
    created_date = models.DateTimeField(
        auto_now_add=True
    )

    def __str__(self):
        return 'Albumlike (User: {user}, Album{album}), Created{created}'.format(
            # return '"{album}"가수의 좋아요를 누른({username}, {date})'.format(
            album=self.album.name,
            user=self.user.username,
            created=datetime.strftime(self.created_date, '%y.%m.%d'),
        )

    class Meta:
        unique_together = (
            ('album', 'user'),
        )
        # 좋아요가 중복으로 되는것을 방지

django/album/forms.py
from django.forms import ModelForm
from django import forms

from album.models import Album

__all__ = (
    'AlbumForm'
)


class AlbumForm(forms.ModelForm):
    class Meta:
        model = Album
        fields = ['title', 'img_cover', 'release_date']
        widgets = {
            'name': forms.TextInput(
                attrs={
                    'class': 'form-control',
                }
            )
        }

django/album/views.py
from django.shortcuts import render
from .models import Album


# Create your views here.
def album_list(request):
    albums = Album.objects.all()
    context = {
        'albums': albums,
    }
    # 전체 Artist목록을 ul>li로 출력
    # 템플릿은 'artist/list.html'을 사용
    # 전달할 context키는 'artist'를 사용

    return render(request, 'album/album_list.html', context)

django/templates/album/album.html
{% extends 'base.html' %}

{% block title %}album list{% endblock %}

{% block contents%}
<div>
    <ul>
         {% for album in albums%}
        <li> {{album.name}}</li>

        {% endfor %}
    </ul>
</div>
{% endblock %}}

django/templates/album/album_add.html
{% extends 'base.html' %}

{% block content %}
<div>
	<h3>직접 앨범 추가</h3>
	<form action="" method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		{% for field in album_form %}
			<div>
				<label for="{{ field.id_for_label }}">{{ field.label }}</label>
				{{ field }}
				{% if field.errors %}
				<ul>
					{% for error in field.errors %}
					<li>{{ error }}</li>
					{% endfor %}
				</ul>
				{% endif %}
			</div>
		{% endfor %}
		<button type="submit">등록</button>
	</form>

	<hr>

	<h3>멜론에서 앨범 검색</h3>
	<form action="{% url 'album:album-search-from-melon' %}">
		<input type="text" name="keyword" placeholder="앨범명">
		<button type="submit">검색</button>
	</form>

</div>
{% endblock %}

django/templates/album/album_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="album-list-container">
	<!-- album-add로의 링크 생성 -->
	<a href="{% url 'album:album-add' %}">앨범 추가</a>
	<ul class="clearfix">
		<li class="clearfix">
			<a href="">
				<img src="{% if album.img_cover %}{{ album.img_cover.url }}{% endif %}" alt="" class="cover">
				<div class="album-info">
					<div class="name">{{ album.title}}</div>
					<div>{{ album.release_date }}</div>
				</div>

				{% if request.user.is_authenticated %}
				<!-- artist_like_toggle을 실행할 form -->
				<form action="{% url 'album:album-like-toggle' album_pk=album.pk %}" method="POST">
					{% csrf_token %}
					<input type="hidden" name="next-path" value="{{ request.get_full_path }}">
					{% if album.user in album.like_users.all %}
						<button type="submit">좋아요 취소</button>
					{% else %}
						<button type="submit">좋아요</button>
					{% endif %}
				</form>
				{% endif %}
			</a>
		</li>
	</ul>
</div>
{% endblock %}

django/templates/album/album_edit.html
{% extends 'base.html' %}

{% block content %}
<div>
	<form action="" method="POST">
		{% csrf_token %}
		{% for field in album_form %}
			<div>
				<label for="{{ field.id_for_label }}">{{ field.label }}</label>
				{{ field }}
				{% if field.errors %}
				<ul>
					{% for error in field.errors %}
					<li>{{ error }}</li>
					{% endfor %}
				</ul>
				{% endif %}
			</div>
		{% endfor %}
		<button type="submit">수정</button>
	</form>
</div>
{% endblock %}

django/templates/album/album_list.html
{% extends 'base.html' %}

{% block title %}album list{% endblock %}

{% block contents%}
<div>
    <ul>
         {% for album in albums%}
        <li> {{album.name}}</li>

        {% endfor %}
    </ul>
</div>
{% endblock %}}

django/templates/album/album_search_from_melon.html
{% extends 'base.html' %}

{% block content %}
<div>
    <h3>멜론에서 앨범 검색</h3>
    <form action="">
        <input type="text" name="keyword" placeholder="앨범명">
        <button type="submit">검색</button>
    </form>

    <ul>
        {% for album_info in album_info_list %}
        <li>
            <img src="{{ album_info.url_img_cover }}" alt="">
            <span>{{ album_info.album_id}} | {{ album_info.title }}</span>
            <form action="{% url 'album:album-add-from-melon' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="album_id" value="{{ album_info.album_id }}">
                <!--
                만약 DB에 있는 데이터일 경우에는 DB업데이트라는 문자열을 버튼의 텍스트로 사용
                -->
                {% if album_info.is_update %}
                    <button type="submit">DB에 업데이트</button>
                {% else %}
                    <button type="submit">DB에 추가하기</button>
                {% endif %}
                <!--<button type="submit">DB에 추가하기</button>-->
            </form>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}